<?xml version="1.0"?>
<package format="3">
  <name>kufibot_bringup</name>
  <version>0.1.0</version>
  <description>System launch files and deployment configuration for Kufibot.</description>
  <maintainer email="y.bulbul@hotmail.com">kufi</maintainer>
  <license>BSD-2-Clause</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>kufibot_sensors</exec_depend>
  <exec_depend>kufibot_actuators</exec_depend>
  <exec_depend>kufibot_perception</exec_depend>
  <exec_depend>kufibot_interaction</exec_depend>
  <exec_depend>kufibot_remote</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
