[pytest]
testpaths =
    src/kufibot_interaction/test
    src/kufibot_perception/test
python_files = test_*.py
addopts = --import-mode=importlib
norecursedirs = build install log .venv .git manual
pythonpath =
    src/kufibot_actuators
    src/kufibot_sensors
    src/kufibot_perception
    src/kufibot_interaction
