# generated by datamodel-codegen:
#   filename:  verasist-openapi-NsS4EB.json
#   timestamp: 2026-08-27T15:09:39+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class CalculatorToolDefinition(BaseModel):
    """
    Tool definition for Calculator tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['calculator'], Field(title='Type')]
    """
    Tool type.
    """


class EntryType(Enum):
    """
    The default type of calendar entry this tool creates.
    """

    note = 'note'
    appointment = 'appointment'
    reminder = 'reminder'
    todo = 'todo'
    trigger = 'trigger'


class CallbackChannel(Enum):
    """
    Dispatch channel used when the assistant schedules a callback trigger. Only relevant when enable_callback_scheduling is true.
    """

    phone = 'phone'
    whatsapp = 'whatsapp'
    telegram = 'telegram'
    instagram = 'instagram'
    text = 'text'


class CustomMessageType(Enum):
    """
    Type of custom message.
    """

    text = 'text'
    audio = 'audio'


class CalendarConfig(BaseModel):
    """
    Configuration for Calendar tools.
    """

    entry_type: Annotated[EntryType | None, Field(title='Entry Type')] = 'note'
    """
    The default type of calendar entry this tool creates.
    """
    default_title_template: Annotated[
        str | None, Field(title='Default Title Template')
    ] = None
    """
    Optional template for the entry title. Supports {{template_variables}}.
    """
    enable_callback_scheduling: Annotated[
        bool | None, Field(title='Enable Callback Scheduling')
    ] = False
    """
    Allow the assistant to schedule a trigger (e.g. a callback to the current caller) via this tool during a live conversation.
    """
    callback_channel: Annotated[
        CallbackChannel | None, Field(title='Callback Channel')
    ] = 'phone'
    """
    Dispatch channel used when the assistant schedules a callback trigger. Only relevant when enable_callback_scheduling is true.
    """
    callback_channel_configuration_id: Annotated[
        int | None, Field(title='Callback Channel Configuration Id')
    ] = None
    """
    Channel configuration id to send through — required when callback_channel is whatsapp, telegram, or instagram.
    """
    callback_telephony_configuration_id: Annotated[
        int | None, Field(title='Callback Telephony Configuration Id')
    ] = None
    """
    Telephony configuration id to dial through when callback_channel is phone. Leave unset to use the organization's default telephony configuration.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class CalendarEntryResponse(BaseModel):
    """
    Public response for a calendar entry.
    """

    id: Annotated[int, Field(title='Id')]
    entry_uuid: Annotated[str, Field(title='Entry Uuid')]
    entry_type: Annotated[str, Field(title='Entry Type')]
    date: Annotated[str, Field(title='Date')]
    end_date: Annotated[str | None, Field(title='End Date')] = None
    time: Annotated[str | None, Field(title='Time')] = None
    title: Annotated[str, Field(title='Title')]
    description: Annotated[str | None, Field(title='Description')] = None
    source_tool_uuid: Annotated[str | None, Field(title='Source Tool Uuid')] = None
    source_workflow_run_id: Annotated[
        int | None, Field(title='Source Workflow Run Id')
    ] = None
    action_type: Annotated[str | None, Field(title='Action Type')] = None
    action_target_type: Annotated[str | None, Field(title='Action Target Type')] = None
    action_target_id: Annotated[int | None, Field(title='Action Target Id')] = None
    action_target_uuid: Annotated[str | None, Field(title='Action Target Uuid')] = None
    action_mode: Annotated[str | None, Field(title='Action Mode')] = None
    action_channel: Annotated[str | None, Field(title='Action Channel')] = None
    action_channel_configuration_id: Annotated[
        int | None, Field(title='Action Channel Configuration Id')
    ] = None
    action_telephony_configuration_id: Annotated[
        int | None, Field(title='Action Telephony Configuration Id')
    ] = None
    action_target: Annotated[str | None, Field(title='Action Target')] = None
    recurrence_rule: Annotated[
        dict[str, Any] | None, Field(title='Recurrence Rule')
    ] = None
    trigger_status: Annotated[str | None, Field(title='Trigger Status')] = None
    next_trigger_at: Annotated[str | None, Field(title='Next Trigger At')] = None
    triggered_at: Annotated[str | None, Field(title='Triggered At')] = None
    trigger_error: Annotated[str | None, Field(title='Trigger Error')] = None
    created_at: Annotated[str, Field(title='Created At')]
    updated_at: Annotated[str, Field(title='Updated At')]


class CalendarToolDefinition(BaseModel):
    """
    Tool definition for Calendar tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['calendar'], Field(title='Type')]
    """
    Tool type.
    """
    config: CalendarConfig | None = None
    """
    Calendar configuration.
    """


class CallDispositionCodes(BaseModel):
    disposition_codes: Annotated[list[str] | None, Field(title='Disposition Codes')] = (
        []
    )


class CallHistoryConfig(BaseModel):
    """
    Configuration for Call History tools.

    A call history tool lets the agent look up past workflow runs
    (outbound calls) associated with the current caller's phone number.
    The caller number is always taken from the current call context —
    the tool never exposes arbitrary phone-number search to the LLM.
    """

    max_results: Annotated[int | None, Field(ge=1, le=50, title='Max Results')] = 10
    """
    Maximum number of past call records to return.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class CallHistoryToolDefinition(BaseModel):
    """
    Tool definition for Call History tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['call_history'], Field(title='Type')]
    """
    Tool type.
    """
    config: CallHistoryConfig | None = None
    """
    Call history configuration.
    """


class CampaignRangeResponse(BaseModel):
    """
    Public response for a campaign date range shown on the calendar.
    """

    campaign_id: Annotated[int, Field(title='Campaign Id')]
    campaign_name: Annotated[str, Field(title='Campaign Name')]
    state: Annotated[str, Field(title='State')]
    started_at: Annotated[str | None, Field(title='Started At')] = None
    completed_at: Annotated[str | None, Field(title='Completed At')] = None
    workflow_name: Annotated[str | None, Field(title='Workflow Name')] = None


class ChannelOutboundInitiateRequest(BaseModel):
    channel_type: Annotated[str, Field(title='Channel Type')]
    """
    Channel type (e.g. 'whatsapp')
    """
    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    Channel config ID to use
    """
    mode: Annotated[str, Field(title='Mode')]
    """
    'voice' or 'chat'
    """
    target: Annotated[str, Field(title='Target')]
    """
    Channel-specific target identity (phone number, username)
    """
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    """
    Workflow ID to execute
    """


class Category(Enum):
    """
    Tool category. Must match definition.type.
    """

    http_api = 'http_api'
    web_page_query = 'web_page_query'
    end_call = 'end_call'
    transfer_call = 'transfer_call'
    calculator = 'calculator'
    calendar = 'calendar'
    call_history = 'call_history'
    transfer_to_assistant = 'transfer_to_assistant'
    send_message = 'send_message'
    transfer_to_channel = 'transfer_to_channel'
    native = 'native'
    integration = 'integration'
    mcp = 'mcp'
    email = 'email'
    google_tasks = 'google_tasks'
    google_calendar = 'google_calendar'
    google_sheets = 'google_sheets'
    incoming_messages = 'incoming_messages'
    trendyol = 'trendyol'
    yemeksepeti = 'yemeksepeti'
    crm = 'crm'
    media_generation = 'media_generation'
    instagram_post = 'instagram_post'
    facebook_post = 'facebook_post'
    linkedin_post = 'linkedin_post'
    tiktok_post = 'tiktok_post'
    threads_post = 'threads_post'
    x_post = 'x_post'
    wordpress_post = 'wordpress_post'


class Icon(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Icon')] = 'globe'
    """
    Lucide icon identifier.
    """


class IconColor(RootModel[str]):
    root: Annotated[str, Field(max_length=7, title='Icon Color')] = '#3B82F6'
    """
    Hex color for the tool icon.
    """


class CreateWorkflowRequest(BaseModel):
    name: Annotated[str, Field(title='Name')]
    workflow_definition: Annotated[dict[str, Any], Field(title='Workflow Definition')]


class CreatedByResponse(BaseModel):
    """
    Response schema for the user who created a tool.
    """

    id: Annotated[int, Field(title='Id')]
    provider_id: Annotated[str, Field(title='Provider Id')]


class CredentialResponse(BaseModel):
    """
    Response schema for a webhook credential (never includes sensitive data).
    """

    uuid: Annotated[str, Field(title='Uuid')]
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')]
    credential_type: Annotated[str, Field(title='Credential Type')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime | None, Field(title='Updated At')]


class CrmConfig(BaseModel):
    """
    Configuration for the CRM tool.

    Searches, creates, updates, and lists contacts, during a live
    conversation, through a previously connected CRM account (HubSpot or
    Microsoft Dynamics 365). The account is fixed when the tool is
    configured; the LLM only supplies contact details at call time.
    """

    crm_config_id: Annotated[int, Field(title='Crm Config Id')]
    """
    ID of the CRM configuration (connected HubSpot/Dynamics 365 account) to use.
    """
    allow_search: Annotated[bool | None, Field(title='Allow Search')] = True
    """
    Whether the agent may search for a contact by email/phone through this tool.
    """
    allow_create: Annotated[bool | None, Field(title='Allow Create')] = True
    """
    Whether the agent may create contacts through this tool.
    """
    allow_update: Annotated[bool | None, Field(title='Allow Update')] = True
    """
    Whether the agent may update contacts through this tool.
    """
    allow_list: Annotated[bool | None, Field(title='Allow List')] = True
    """
    Whether the agent may list recent contacts through this tool.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class CrmToolDefinition(BaseModel):
    """
    Tool definition for CRM tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['crm'], Field(title='Type')]
    """
    Tool type.
    """
    config: CrmConfig
    """
    CRM configuration.
    """


class DeviceToolSchema(BaseModel):
    """
    JSON-schema describing a tool implemented on the device (SDK) side.

    These are not persisted as DB `Tool` rows — they are ephemeral,
    per-session declarations sent by the SDK client and merged into the
    LLM's function list for the lifetime of the live session only.
    """

    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')] = ''
    parameters: Annotated[dict[str, Any] | None, Field(title='Parameters')] = None


class DisplayOptions(BaseModel):
    """
    Conditional visibility rules.

    `show` keys are AND-combined: this property is visible only when EVERY
    referenced field's value matches one of the listed values.

    `hide` keys are OR-combined: this property is hidden when ANY referenced
    field's value matches one of the listed values.

    Example:
        DisplayOptions(show={"extraction_enabled": [True]})
        DisplayOptions(show={"greeting_type": ["audio"]})
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    show: Annotated[dict[str, list[Any]] | None, Field(title='Show')] = None
    hide: Annotated[dict[str, list[Any]] | None, Field(title='Hide')] = None


class DocumentResponseSchema(BaseModel):
    """
    Response schema for document metadata.
    """

    id: Annotated[int, Field(title='Id')]
    document_uuid: Annotated[str, Field(title='Document Uuid')]
    filename: Annotated[str, Field(title='Filename')]
    file_size_bytes: Annotated[int, Field(title='File Size Bytes')]
    file_hash: Annotated[str, Field(title='File Hash')]
    mime_type: Annotated[str, Field(title='Mime Type')]
    processing_status: Annotated[str, Field(title='Processing Status')]
    processing_error: Annotated[str | None, Field(title='Processing Error')] = None
    total_chunks: Annotated[int, Field(title='Total Chunks')]
    retrieval_mode: Annotated[str | None, Field(title='Retrieval Mode')] = 'chunked'
    custom_metadata: Annotated[dict[str, Any], Field(title='Custom Metadata')]
    docling_metadata: Annotated[dict[str, Any], Field(title='Docling Metadata')]
    source_url: Annotated[str | None, Field(title='Source Url')] = None
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    organization_id: Annotated[int, Field(title='Organization Id')]
    created_by: Annotated[int, Field(title='Created By')]
    is_active: Annotated[bool, Field(title='Is Active')]
    sendable_to_user: Annotated[bool | None, Field(title='Sendable To User')] = False


class EmailConfig(BaseModel):
    """
    Configuration for the Email tool.

    Sends and/or reads email, during a live conversation, through a
    previously connected mailbox (Gmail or Microsoft). The mailbox is
    fixed when the tool is configured; the LLM only supplies the
    message contents / search terms at call time.
    """

    email_config_id: Annotated[int, Field(title='Email Config Id')]
    """
    ID of the email configuration (connected mailbox) to use. Selected from the organization's connected Gmail/Microsoft accounts.
    """
    allow_send: Annotated[bool | None, Field(title='Allow Send')] = True
    """
    Whether the agent may send email through this tool.
    """
    allow_read: Annotated[bool | None, Field(title='Allow Read')] = True
    """
    Whether the agent may search/read email through this tool.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class EmailToolDefinition(BaseModel):
    """
    Tool definition for Email tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['email'], Field(title='Type')]
    """
    Tool type.
    """
    config: EmailConfig
    """
    Email configuration.
    """


class MessageType(Enum):
    """
    Type of goodbye message.
    """

    none = 'none'
    custom = 'custom'
    audio = 'audio'


class EndCallConfig(BaseModel):
    """
    Configuration for End Call tools.
    """

    messageType: Annotated[MessageType | None, Field(title='Messagetype')] = 'none'
    """
    Type of goodbye message.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before ending the call.
    """
    audioRecordingId: Annotated[str | None, Field(title='Audiorecordingid')] = None
    """
    Recording ID for audio goodbye message.
    """
    endCallReason: Annotated[bool | None, Field(title='Endcallreason')] = False
    """
    When enabled, the model must provide a reason for ending the call. The reason is set as call disposition and added to call tags.
    """
    endCallReasonDescription: Annotated[
        str | None, Field(title='Endcallreasondescription')
    ] = None
    """
    Description shown to the model for the reason parameter. Used only when endCallReason is enabled.
    """


class EndCallToolDefinition(BaseModel):
    """
    Tool definition for End Call tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['end_call'], Field(title='Type')]
    """
    Tool type.
    """
    config: EndCallConfig
    """
    End Call configuration.
    """


class FacebookPostConfig(BaseModel):
    """
    Configuration for the Facebook Post tool.

    Publishes image or video posts and reads/replies to comments, during a
    live conversation, through a previously connected Facebook Page (connected
    via the Meta Graph API OAuth flow on the Channels page). The Page is fixed
    when the tool is configured; the LLM only supplies post/comment contents
    at call time.
    """

    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    ID of the Facebook channel configuration (connected Facebook Page) to use.
    """
    allow_publish: Annotated[bool | None, Field(title='Allow Publish')] = True
    """
    Whether the agent may publish image or video posts through this tool.
    """
    allow_video_posts: Annotated[bool | None, Field(title='Allow Video Posts')] = True
    """
    Whether the agent may publish video posts, in addition to images, when allow_publish is enabled.
    """
    allow_read_comments: Annotated[bool | None, Field(title='Allow Read Comments')] = (
        True
    )
    """
    Whether the agent may list recent posts and read their comments.
    """
    allow_reply_comments: Annotated[
        bool | None, Field(title='Allow Reply Comments')
    ] = True
    """
    Whether the agent may reply to comments through this tool.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class FacebookPostToolDefinition(BaseModel):
    """
    Tool definition for Facebook Post tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['facebook_post'], Field(title='Type')]
    """
    Tool type.
    """
    config: FacebookPostConfig
    """
    Facebook Post configuration.
    """


class GoogleCalendarConfig(BaseModel):
    """
    Configuration for the Google Calendar tool.

    Creates, checks, updates, and cancels events, during a live
    conversation, through a previously connected Google account. The
    account is fixed when the tool is configured; the LLM only supplies
    event contents / time ranges at call time.
    """

    google_config_id: Annotated[int, Field(title='Google Config Id')]
    """
    ID of the Google integration configuration (connected Google Calendar account) to use.
    """
    allow_create: Annotated[bool | None, Field(title='Allow Create')] = True
    """
    Whether the agent may create events through this tool.
    """
    allow_list: Annotated[bool | None, Field(title='Allow List')] = True
    """
    Whether the agent may list events / check availability through this tool.
    """
    allow_update: Annotated[bool | None, Field(title='Allow Update')] = True
    """
    Whether the agent may update events through this tool.
    """
    allow_cancel: Annotated[bool | None, Field(title='Allow Cancel')] = True
    """
    Whether the agent may cancel events through this tool.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class GoogleCalendarToolDefinition(BaseModel):
    """
    Tool definition for Google Calendar tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['google_calendar'], Field(title='Type')]
    """
    Tool type.
    """
    config: GoogleCalendarConfig
    """
    Google Calendar configuration.
    """


class GoogleSheetsConfig(BaseModel):
    """
    Configuration for the Google Sheets tool.

    Appends, reads, and updates rows, during a live conversation, in a
    fixed spreadsheet through a previously connected Google account. The
    account and spreadsheet are fixed when the tool is configured; the
    LLM only supplies row values / lookup criteria at call time.
    """

    google_config_id: Annotated[int, Field(title='Google Config Id')]
    """
    ID of the Google integration configuration (connected Google Sheets account) to use.
    """
    spreadsheet_id: Annotated[str, Field(min_length=1, title='Spreadsheet Id')]
    """
    Fixed target spreadsheet ID (from the Google Sheets URL).
    """
    sheet_name: Annotated[str | None, Field(title='Sheet Name')] = 'Sheet1'
    """
    Fixed target sheet/tab name within the spreadsheet, used to build A1 ranges.
    """
    allow_append: Annotated[bool | None, Field(title='Allow Append')] = True
    """
    Whether the agent may append rows through this tool.
    """
    allow_read: Annotated[bool | None, Field(title='Allow Read')] = True
    """
    Whether the agent may read rows through this tool.
    """
    allow_update: Annotated[bool | None, Field(title='Allow Update')] = True
    """
    Whether the agent may update rows through this tool.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class GoogleSheetsToolDefinition(BaseModel):
    """
    Tool definition for Google Sheets tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['google_sheets'], Field(title='Type')]
    """
    Tool type.
    """
    config: GoogleSheetsConfig
    """
    Google Sheets configuration.
    """


class GoogleTasksConfig(BaseModel):
    """
    Configuration for the Google Tasks tool.

    Creates, lists, and completes tasks, during a live conversation,
    through a previously connected Google account. The account is fixed
    when the tool is configured; the LLM only supplies task contents at
    call time.
    """

    google_config_id: Annotated[int, Field(title='Google Config Id')]
    """
    ID of the Google integration configuration (connected Google Tasks account) to use.
    """
    allow_create: Annotated[bool | None, Field(title='Allow Create')] = True
    """
    Whether the agent may create tasks through this tool.
    """
    allow_list: Annotated[bool | None, Field(title='Allow List')] = True
    """
    Whether the agent may list tasks through this tool.
    """
    allow_complete: Annotated[bool | None, Field(title='Allow Complete')] = True
    """
    Whether the agent may mark tasks completed through this tool.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class GoogleTasksToolDefinition(BaseModel):
    """
    Tool definition for Google Tasks tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['google_tasks'], Field(title='Type')]
    """
    Tool type.
    """
    config: GoogleTasksConfig
    """
    Google Tasks configuration.
    """


class GraphConstraints(BaseModel):
    """
    Per-node-type graph rules. WorkflowGraph enforces these at validation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    min_incoming: Annotated[int | None, Field(title='Min Incoming')] = None
    max_incoming: Annotated[int | None, Field(title='Max Incoming')] = None
    min_outgoing: Annotated[int | None, Field(title='Min Outgoing')] = None
    max_outgoing: Annotated[int | None, Field(title='Max Outgoing')] = None


class Method(Enum):
    """
    HTTP method to use for the request.
    """

    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'


class TimeoutMs(RootModel[int]):
    root: Annotated[int, Field(ge=1, title='Timeout Ms')] = 5000
    """
    Request timeout in milliseconds.
    """


class IncomingMessagesToolDefinition(BaseModel):
    """
    Tool definition for inbound social-channel message lookup.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['incoming_messages'], Field(title='Type')]
    """
    Tool type.
    """
    config: Annotated[dict[str, Any] | None, Field(title='Config')] = None
    """
    Incoming message lookup configuration.
    """


class InitiateCallRequest(BaseModel):
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    workflow_run_id: Annotated[int | None, Field(title='Workflow Run Id')] = None
    phone_number: Annotated[str | None, Field(title='Phone Number')] = None
    telephony_configuration_id: Annotated[
        int | None, Field(title='Telephony Configuration Id')
    ] = None
    from_phone_number_id: Annotated[int | None, Field(title='From Phone Number Id')] = (
        None
    )


class InstagramPostConfig(BaseModel):
    """
    Configuration for the Instagram Post tool.

    Publishes image or Reels (video) posts and reads/replies to comments,
    during a live conversation, through a previously connected Instagram
    channel (connected via the Instagram Graph API OAuth flow on the
    Channels page). The account is fixed when the tool is configured; the
    LLM only supplies post/comment contents at call time.
    """

    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    ID of the Instagram channel configuration (connected Instagram Business account) to use.
    """
    allow_publish: Annotated[bool | None, Field(title='Allow Publish')] = True
    """
    Whether the agent may publish image or Reels (video) posts through this tool.
    """
    allow_video_posts: Annotated[bool | None, Field(title='Allow Video Posts')] = True
    """
    Whether the agent may publish Reels (video) posts, in addition to images, when allow_publish is enabled.
    """
    allow_read_comments: Annotated[bool | None, Field(title='Allow Read Comments')] = (
        True
    )
    """
    Whether the agent may list recent posts and read their comments.
    """
    allow_reply_comments: Annotated[
        bool | None, Field(title='Allow Reply Comments')
    ] = True
    """
    Whether the agent may reply to comments through this tool.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class InstagramPostToolDefinition(BaseModel):
    """
    Tool definition for Instagram Post tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['instagram_post'], Field(title='Type')]
    """
    Tool type.
    """
    config: InstagramPostConfig
    """
    Instagram Post configuration.
    """


class LinkedInPostConfig(BaseModel):
    """
    Configuration for the LinkedIn Post tool.

    Publishes text, image, or video posts during a live conversation, through
    a previously connected LinkedIn channel (connected via the LinkedIn OAuth
    flow on the Channels page). The member is fixed when the tool is
    configured; the LLM only supplies post contents at call time.
    """

    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    ID of the LinkedIn channel configuration (connected LinkedIn member profile) to use.
    """
    allow_publish: Annotated[bool | None, Field(title='Allow Publish')] = True
    """
    Whether the agent may publish text or image posts through this tool.
    """
    allow_video_posts: Annotated[bool | None, Field(title='Allow Video Posts')] = True
    """
    Whether the agent may publish video posts, in addition to text and images, when allow_publish is enabled.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class LinkedInPostToolDefinition(BaseModel):
    """
    Tool definition for LinkedIn Post tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['linkedin_post'], Field(title='Type')]
    """
    Tool type.
    """
    config: LinkedInPostConfig
    """
    LinkedIn Post configuration.
    """


class McpToolConfig(BaseModel):
    """
    Configuration for a customer MCP server tool definition.
    """

    transport: Annotated[Literal['streamable_http'], Field(title='Transport')] = (
        'streamable_http'
    )
    """
    MCP transport protocol.
    """
    url: Annotated[str, Field(title='Url')]
    """
    MCP server URL. Must use http:// or https://.
    """
    credential_uuid: Annotated[str | None, Field(title='Credential Uuid')] = None
    """
    Reference to an external credential for MCP server auth.
    """
    tools_filter: Annotated[list[str] | None, Field(title='Tools Filter')] = None
    """
    Allowlist of MCP tool names to expose. Empty exposes all tools.
    """
    timeout_secs: Annotated[int | None, Field(ge=0, title='Timeout Secs')] = 30
    """
    Connection timeout in seconds.
    """
    sse_read_timeout_secs: Annotated[
        int | None, Field(ge=0, title='Sse Read Timeout Secs')
    ] = 300
    """
    SSE read timeout in seconds.
    """
    discovered_tools: Annotated[
        list[dict[str, Any]] | None, Field(title='Discovered Tools')
    ] = None
    """
    Server-managed cache of the MCP server's tool catalog [{name, description}]. Populated best-effort by the backend.
    """


class McpToolDefinition(BaseModel):
    """
    Persisted MCP tool definition.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['mcp'], Field(title='Type')]
    """
    Tool type.
    """
    config: McpToolConfig
    """
    MCP server configuration.
    """


class MediaType(Enum):
    image = 'image'
    video = 'video'


class ImageProvider(Enum):
    """
    Provider used for image generation.
    """

    openai = 'openai'
    google = 'google'


class ImageModel(RootModel[str]):
    root: Annotated[str, Field(max_length=128, title='Image Model')]
    """
    Provider model used for image generation.
    """


class VideoProvider(Enum):
    """
    Provider used for video generation.
    """

    openai = 'openai'
    google = 'google'


class VideoModel(RootModel[str]):
    root: Annotated[str, Field(max_length=128, title='Video Model')]
    """
    Provider model used for video generation.
    """


class CustomMessageType11(Enum):
    """
    Type of the media generation wait message.
    """

    text = 'text'
    audio = 'audio'


class MediaGenerationConfig(BaseModel):
    """
    Configuration for image and video generation tools.
    """

    media_types: Annotated[
        list[MediaType] | None, Field(min_length=1, title='Media Types')
    ] = None
    """
    Media types that the assistant may generate.
    """
    image_provider: Annotated[ImageProvider | None, Field(title='Image Provider')] = (
        None
    )
    """
    Provider used for image generation.
    """
    image_model: Annotated[ImageModel | None, Field(title='Image Model')] = None
    """
    Provider model used for image generation.
    """
    video_provider: Annotated[VideoProvider | None, Field(title='Video Provider')] = (
        None
    )
    """
    Provider used for video generation.
    """
    video_model: Annotated[VideoModel | None, Field(title='Video Model')] = None
    """
    Provider model used for video generation.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Message to play while media generation is in progress.
    """
    customMessageType: Annotated[
        CustomMessageType11 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of the media generation wait message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio media generation wait message.
    """


class MediaGenerationToolDefinition(BaseModel):
    """
    Tool definition for image and video generation.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['media_generation'], Field(title='Type')]
    """
    Tool type.
    """
    config: MediaGenerationConfig
    """
    Media generation configuration.
    """


class NodeCategory(Enum):
    """
    Drives grouping in the AddNodePanel UI.
    """

    call_node = 'call_node'
    global_node = 'global_node'
    trigger = 'trigger'
    integration = 'integration'


class NodeExample(BaseModel):
    """
    A worked example LLMs can pattern-match. Keep small and realistic.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')] = None
    data: Annotated[dict[str, Any], Field(title='Data')]


class Type(Enum):
    """
    JSON type for the resolved value.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    object = 'object'
    array = 'array'


class PresetToolParameter(BaseModel):
    """
    A parameter injected by Verasist at runtime.
    """

    name: Annotated[str, Field(title='Name')]
    """
    Parameter name used as a key in the request body.
    """
    type: Annotated[Type, Field(title='Type')]
    """
    JSON type for the resolved value.
    """
    value_template: Annotated[str, Field(title='Value Template')]
    """
    Fixed value or template, e.g. {{initial_context.phone_number}}.
    """
    required: Annotated[bool | None, Field(title='Required')] = True
    """
    Whether the parameter must resolve to a non-empty value.
    """


class PropertyOption(BaseModel):
    """
    An option in an `options` or `multi_options` dropdown.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[str | int | bool | float, Field(title='Value')]
    label: Annotated[str, Field(title='Label')]
    description: Annotated[str | None, Field(title='Description')] = None


class PropertyType(Enum):
    """
    Bounded vocabulary of property types the renderer dispatches on.

    Adding a value here requires a matching arm in the frontend
    `<PropertyInput>` switch and (where relevant) the SDK codegen template.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    options = 'options'
    multi_options = 'multi_options'
    fixed_collection = 'fixed_collection'
    json = 'json'
    tool_refs = 'tool_refs'
    document_refs = 'document_refs'
    recording_ref = 'recording_ref'
    credential_ref = 'credential_ref'
    mention_textarea = 'mention_textarea'
    url = 'url'


class RecordingResponseSchema(BaseModel):
    """
    Response schema for a single recording.
    """

    id: Annotated[int, Field(title='Id')]
    recording_id: Annotated[str, Field(title='Recording Id')]
    workflow_id: Annotated[int | None, Field(title='Workflow Id')] = None
    organization_id: Annotated[int, Field(title='Organization Id')]
    tts_provider: Annotated[str | None, Field(title='Tts Provider')] = None
    tts_model: Annotated[str | None, Field(title='Tts Model')] = None
    tts_voice_id: Annotated[str | None, Field(title='Tts Voice Id')] = None
    transcript: Annotated[str, Field(title='Transcript')]
    storage_key: Annotated[str, Field(title='Storage Key')]
    storage_backend: Annotated[str, Field(title='Storage Backend')]
    metadata: Annotated[dict[str, Any], Field(title='Metadata')]
    created_by: Annotated[int, Field(title='Created By')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    is_active: Annotated[bool, Field(title='Is Active')]


class RecurrenceRule(BaseModel):
    """
    Simple recurrence definition for trigger entries.
    """

    frequency: Annotated[str, Field(title='Frequency')]
    """
    Recurrence frequency: daily, weekly, monthly.
    """
    interval: Annotated[int | None, Field(ge=1, title='Interval')] = 1
    """
    Interval for the frequency.
    """
    days_of_week: Annotated[list[int] | None, Field(title='Days Of Week')] = None
    """
    Days of week (0=Monday) for weekly recurrence.
    """
    end_date: Annotated[str | None, Field(title='End Date')] = None
    """
    Optional end date in YYYY-MM-DD format.
    """


class CustomMessageType12(Enum):
    """
    Type of custom message.
    """

    text = 'text'
    audio = 'audio'


class SendMessageConfig(BaseModel):
    """
    Configuration for the Send Message tool.

    Sends a text message, during a live conversation, through a
    previously configured chat channel (WhatsApp, Telegram, Instagram).
    The channel is fixed when the tool is configured; the LLM only
    supplies the recipient identity and message text at call time.
    """

    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    ID of the channel configuration to send through. Selected from the organization's configured channels.
    """
    channel_type: Annotated[str, Field(title='Channel Type')]
    """
    Channel type of the selected configuration (e.g. whatsapp, telegram, instagram). Stored alongside channel_configuration_id so the tool schema can be tailored per channel without a DB call.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class SendMessageToolDefinition(BaseModel):
    """
    Tool definition for Send Message tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['send_message'], Field(title='Type')]
    """
    Tool type.
    """
    config: SendMessageConfig
    """
    Send Message configuration.
    """


class StartLiveSessionRequest(BaseModel):
    """
    Request body for starting a device live voice session.
    """

    initial_context: Annotated[
        dict[str, Any] | None, Field(title='Initial Context')
    ] = None
    device_tools: Annotated[
        list[DeviceToolSchema] | None, Field(title='Device Tools')
    ] = None


class StartLiveSessionResponse(BaseModel):
    """
    Response returned after a live session has been created.
    """

    session_token: Annotated[str, Field(title='Session Token')]
    workflow_run_id: Annotated[int, Field(title='Workflow Run Id')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]


class ThreadsPostConfig(BaseModel):
    """
    Configuration for the Threads Post tool.

    Publishes text, image, or video posts and reads a post's replies, during
    a live conversation, through a previously connected Threads channel
    (connected via the Threads OAuth flow on the Channels page). The profile
    is fixed when the tool is configured; the LLM only supplies post/reply
    contents at call time.
    """

    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    ID of the Threads channel configuration (connected Threads profile) to use.
    """
    allow_publish: Annotated[bool | None, Field(title='Allow Publish')] = True
    """
    Whether the agent may publish text, image, or video posts through this tool.
    """
    allow_video_posts: Annotated[bool | None, Field(title='Allow Video Posts')] = True
    """
    Whether the agent may publish video posts, in addition to text and images, when allow_publish is enabled.
    """
    allow_read_replies: Annotated[bool | None, Field(title='Allow Read Replies')] = True
    """
    Whether the agent may list recent posts and read their replies.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class ThreadsPostToolDefinition(BaseModel):
    """
    Tool definition for Threads Post tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['threads_post'], Field(title='Type')]
    """
    Tool type.
    """
    config: ThreadsPostConfig
    """
    Threads Post configuration.
    """


class PrivacyLevel(Enum):
    """
    TikTok privacy level for published videos. Defaults to SELF_ONLY, which is required for apps that have not passed TikTok's audit. Use PUBLIC_TO_EVERYONE only after your app is audited.
    """

    SELF_ONLY = 'SELF_ONLY'
    MUTUAL_FOLLOW_FRIENDS = 'MUTUAL_FOLLOW_FRIENDS'
    PUBLIC_TO_EVERYONE = 'PUBLIC_TO_EVERYONE'


class TikTokPostConfig(BaseModel):
    """
    Configuration for the TikTok Post tool.

    Publishes videos during a live conversation, through a previously
    connected TikTok channel (connected via the TikTok OAuth flow on the
    Channels page). The creator is fixed when the tool is configured; the LLM
    only supplies the video and title at call time.
    """

    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    ID of the TikTok channel configuration (connected TikTok creator account) to use.
    """
    allow_publish: Annotated[bool | None, Field(title='Allow Publish')] = True
    """
    Whether the agent may publish videos through this tool.
    """
    privacy_level: Annotated[PrivacyLevel | None, Field(title='Privacy Level')] = (
        'SELF_ONLY'
    )
    """
    TikTok privacy level for published videos. Defaults to SELF_ONLY, which is required for apps that have not passed TikTok's audit. Use PUBLIC_TO_EVERYONE only after your app is audited.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class TikTokPostToolDefinition(BaseModel):
    """
    Tool definition for TikTok Post tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['tiktok_post'], Field(title='Type')]
    """
    Tool type.
    """
    config: TikTokPostConfig
    """
    TikTok Post configuration.
    """


class Type1(Enum):
    """
    JSON type for the parameter value.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    object = 'object'
    array = 'array'


class ToolParameter(BaseModel):
    """
    A parameter that the tool accepts from the model at call time.
    """

    name: Annotated[str, Field(title='Name')]
    """
    Parameter name used as a key in the tool request body.
    """
    type: Annotated[Type1, Field(title='Type')]
    """
    JSON type for the parameter value.
    """
    description: Annotated[str, Field(title='Description')]
    """
    Description shown to the model for this parameter.
    """
    required: Annotated[bool | None, Field(title='Required')] = True
    """
    Whether this parameter is required when the tool is called.
    """


class ToolResponse(BaseModel):
    """
    Response schema for a reusable tool.
    """

    id: Annotated[int, Field(title='Id')]
    tool_uuid: Annotated[str, Field(title='Tool Uuid')]
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')]
    category: Annotated[str, Field(title='Category')]
    icon: Annotated[str | None, Field(title='Icon')]
    icon_color: Annotated[str | None, Field(title='Icon Color')]
    status: Annotated[str, Field(title='Status')]
    definition: Annotated[dict[str, Any], Field(title='Definition')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime | None, Field(title='Updated At')]
    created_by: CreatedByResponse | None = None


class MessageType1(Enum):
    """
    Type of message to play before transfer.
    """

    none = 'none'
    custom = 'custom'
    audio = 'audio'


class TransferCallConfig(BaseModel):
    """
    Configuration for Transfer Call tools.
    """

    destination: Annotated[str, Field(title='Destination')]
    """
    Phone number or SIP endpoint to transfer the call to, e.g. +1234567890 or PJSIP/1234.
    """
    messageType: Annotated[MessageType1 | None, Field(title='Messagetype')] = 'none'
    """
    Type of message to play before transfer.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before transferring.
    """
    audioRecordingId: Annotated[str | None, Field(title='Audiorecordingid')] = None
    """
    Recording ID for audio message before transfer.
    """
    timeout: Annotated[int | None, Field(ge=5, le=120, title='Timeout')] = 30
    """
    Maximum seconds to wait for the destination to answer.
    """


class TransferCallToolDefinition(BaseModel):
    """
    Tool definition for Transfer Call tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['transfer_call'], Field(title='Type')]
    """
    Tool type.
    """
    config: TransferCallConfig
    """
    Transfer Call configuration.
    """


class TransferToAssistantConfig(BaseModel):
    """
    Configuration for the Transfer-to-Assistant tool.

    Transfers the current call/conversation to another workflow
    (assistant). The target assistant starts from its beginning node
    and receives the merged initial context.
    """

    target_workflow_uuid: Annotated[str, Field(title='Target Workflow Uuid')]
    """
    UUID of the target workflow (assistant) to transfer to.
    """
    transfer_message: Annotated[str | None, Field(title='Transfer Message')] = None
    """
    Optional message to play/say before transferring.
    """
    initial_context_mapping: Annotated[
        dict[str, str] | None, Field(title='Initial Context Mapping')
    ] = None
    """
    Optional mapping of source variable names to target variable names for passing context to the target assistant. Source values come from the current call context (initial_context and gathered_context). Example: {"customer_name": "caller_name"} copies customer_name from current context into caller_name for the target assistant.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before transferring.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class TransferToAssistantToolDefinition(BaseModel):
    """
    Tool definition for Transfer-to-Assistant tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['transfer_to_assistant'], Field(title='Type')]
    """
    Tool type.
    """
    config: TransferToAssistantConfig
    """
    Transfer-to-Assistant configuration.
    """


class TransferToChannelConfig(BaseModel):
    """
    Configuration for the Transfer To Channel tool.

    Lets the agent hand off the current conversation — with its full
    message history — to a new conversation on a different messaging
    channel (WhatsApp, Telegram, Instagram). The destination channel and
    the workflow that should run there are fixed when the tool is
    configured; the LLM only supplies the recipient identity at call time.
    """

    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    ID of the destination channel configuration. Selected from the organization's configured channels.
    """
    channel_type: Annotated[str, Field(title='Channel Type')]
    """
    Channel type of the selected configuration (e.g. whatsapp, telegram, instagram). Stored alongside channel_configuration_id so the tool schema can be tailored per channel without a DB call.
    """
    target_workflow_id: Annotated[int, Field(title='Target Workflow Id')]
    """
    ID of the workflow that should run the handed-off conversation on the destination channel.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class TransferToChannelToolDefinition(BaseModel):
    """
    Tool definition for Transfer To Channel tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['transfer_to_channel'], Field(title='Type')]
    """
    Tool type.
    """
    config: TransferToChannelConfig
    """
    Transfer To Channel configuration.
    """


class TrendyolConfig(BaseModel):
    """
    Configuration for the Trendyol tool.

    Answers customer questions and looks up order status, during a live
    conversation, through a previously connected Trendyol seller account.
    The account is fixed when the tool is configured; the LLM only supplies
    question/order details at call time.
    """

    trendyol_config_id: Annotated[int, Field(title='Trendyol Config Id')]
    """
    ID of the Trendyol integration configuration (connected seller account) to use.
    """
    allow_list_questions: Annotated[
        bool | None, Field(title='Allow List Questions')
    ] = True
    """
    Whether the agent may list customer questions through this tool.
    """
    allow_get_question_detail: Annotated[
        bool | None, Field(title='Allow Get Question Detail')
    ] = True
    """
    Whether the agent may fetch a single customer question's detail through this tool.
    """
    allow_answer_questions: Annotated[
        bool | None, Field(title='Allow Answer Questions')
    ] = True
    """
    Whether the agent may answer customer questions through this tool.
    """
    allow_check_order_status: Annotated[
        bool | None, Field(title='Allow Check Order Status')
    ] = True
    """
    Whether the agent may check order status through this tool.
    """
    allow_list_claims: Annotated[bool | None, Field(title='Allow List Claims')] = True
    """
    Whether the agent may list returned/claimed orders through this tool.
    """
    allow_get_claim_issue_reasons: Annotated[
        bool | None, Field(title='Allow Get Claim Issue Reasons')
    ] = True
    """
    Whether the agent may fetch the global list of claim issue/rejection reasons through this tool.
    """
    allow_get_claim_item_audits: Annotated[
        bool | None, Field(title='Allow Get Claim Item Audits')
    ] = True
    """
    Whether the agent may fetch the status/audit history of a single claim item through this tool.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class TrendyolToolDefinition(BaseModel):
    """
    Tool definition for Trendyol tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['trendyol'], Field(title='Type')]
    """
    Tool type.
    """
    config: TrendyolConfig
    """
    Trendyol configuration.
    """


class TurnCredentialsResponse(BaseModel):
    """
    Response model for TURN credentials.
    """

    username: Annotated[str, Field(title='Username')]
    password: Annotated[str, Field(title='Password')]
    ttl: Annotated[int, Field(title='Ttl')]
    uris: Annotated[list[str], Field(title='Uris')]


class UpdateCalendarEntryRequest(BaseModel):
    """
    Request to update a calendar entry.
    """

    entry_type: Annotated[str | None, Field(title='Entry Type')] = None
    date: Annotated[str | None, Field(title='Date')] = None
    end_date: Annotated[str | None, Field(title='End Date')] = None
    time: Annotated[str | None, Field(title='Time')] = None
    title: Annotated[str | None, Field(title='Title')] = None
    description: Annotated[str | None, Field(title='Description')] = None
    action_type: Annotated[str | None, Field(title='Action Type')] = None
    action_target_uuid: Annotated[str | None, Field(title='Action Target Uuid')] = None
    action_mode: Annotated[str | None, Field(title='Action Mode')] = None
    action_channel: Annotated[str | None, Field(title='Action Channel')] = None
    action_channel_configuration_id: Annotated[
        int | None, Field(title='Action Channel Configuration Id')
    ] = None
    action_telephony_configuration_id: Annotated[
        int | None, Field(title='Action Telephony Configuration Id')
    ] = None
    action_target: Annotated[str | None, Field(title='Action Target')] = None
    recurrence_rule: RecurrenceRule | None = None


class UpdateWorkflowRequest(BaseModel):
    name: Annotated[str | None, Field(title='Name')] = None
    workflow_definition: Annotated[
        dict[str, Any] | None, Field(title='Workflow Definition')
    ] = None
    template_context_variables: Annotated[
        dict[str, Any] | None, Field(title='Template Context Variables')
    ] = None
    workflow_configurations: Annotated[
        dict[str, Any] | None, Field(title='Workflow Configurations')
    ] = None


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]
    input: Annotated[Any | None, Field(title='Input')] = None
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None


class WebPageQueryConfig(BaseModel):
    """
    Configuration for direct public web page text extraction.
    """

    max_results: Annotated[int | None, Field(ge=1, le=50, title='Max Results')] = 10
    """
    Maximum number of pages to fetch in parallel.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class WebPageQueryToolDefinition(BaseModel):
    """
    Tool definition for direct public web page text extraction.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['web_page_query'], Field(title='Type')]
    """
    Tool type.
    """
    config: WebPageQueryConfig | None = None
    """
    Web page query configuration.
    """


class DefaultStatus(Enum):
    """
    Post status used when the agent doesn't specify one when publishing/updating.
    """

    draft = 'draft'
    publish = 'publish'
    pending = 'pending'


class WordPressPostConfig(BaseModel):
    """
    Configuration for the WordPress Post tool.

    Publishes/updates blog posts (with categories/tags and featured/inline
    images), lists posts/pages, and uploads media, during a live
    conversation, through a previously connected WordPress site (connected
    via an Application Password on the Channels page). The site is fixed
    when the tool is configured; the LLM only supplies post contents at call
    time.
    """

    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    ID of the WordPress channel configuration (connected site) to use.
    """
    allow_publish_posts: Annotated[bool | None, Field(title='Allow Publish Posts')] = (
        True
    )
    """
    Whether the agent may create new blog posts.
    """
    allow_update_posts: Annotated[bool | None, Field(title='Allow Update Posts')] = True
    """
    Whether the agent may update an existing blog post (by post_id).
    """
    allow_list_content: Annotated[bool | None, Field(title='Allow List Content')] = True
    """
    Whether the agent may list existing blog posts and pages.
    """
    allow_upload_media: Annotated[bool | None, Field(title='Allow Upload Media')] = True
    """
    Whether the agent may upload photos/media to the WordPress media library and attach them (as featured or inline images) to posts.
    """
    default_status: Annotated[DefaultStatus | None, Field(title='Default Status')] = (
        'draft'
    )
    """
    Post status used when the agent doesn't specify one when publishing/updating.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class WordPressPostToolDefinition(BaseModel):
    """
    Tool definition for WordPress Post tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['wordpress_post'], Field(title='Type')]
    """
    Tool type.
    """
    config: WordPressPostConfig
    """
    WordPress Post configuration.
    """


class WorkflowListResponse(BaseModel):
    """
    Lightweight response for workflow listings (excludes large fields).
    """

    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    status: Annotated[str, Field(title='Status')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    total_runs: Annotated[int, Field(title='Total Runs')]
    folder_id: Annotated[int | None, Field(title='Folder Id')] = None
    workflow_uuid: Annotated[str | None, Field(title='Workflow Uuid')] = None


class WorkflowResponse(BaseModel):
    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    status: Annotated[str, Field(title='Status')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    workflow_definition: Annotated[dict[str, Any], Field(title='Workflow Definition')]
    current_definition_id: Annotated[int | None, Field(title='Current Definition Id')]
    template_context_variables: Annotated[
        dict[str, Any] | None, Field(title='Template Context Variables')
    ] = None
    call_disposition_codes: CallDispositionCodes | None = None
    total_runs: Annotated[int | None, Field(title='Total Runs')] = None
    workflow_configurations: Annotated[
        dict[str, Any] | None, Field(title='Workflow Configurations')
    ] = None
    version_number: Annotated[int | None, Field(title='Version Number')] = None
    version_status: Annotated[str | None, Field(title='Version Status')] = None
    workflow_uuid: Annotated[str | None, Field(title='Workflow Uuid')] = None


class XPostConfig(BaseModel):
    """
    Configuration for the X (Twitter) Post tool.

    Publishes text, image, or video posts, reads a post's replies, and replies
    to posts/comments, during a live conversation, through a previously
    connected X channel (connected via the X OAuth flow on the Channels page).
    The account is fixed when the tool is configured; the LLM only supplies
    post/reply contents at call time.
    """

    channel_configuration_id: Annotated[int, Field(title='Channel Configuration Id')]
    """
    ID of the X channel configuration (connected X account) to use.
    """
    allow_publish: Annotated[bool | None, Field(title='Allow Publish')] = True
    """
    Whether the agent may publish text posts through this tool.
    """
    allow_media_posts: Annotated[bool | None, Field(title='Allow Media Posts')] = True
    """
    Whether the agent may attach images or videos to posts, in addition to text, when allow_publish is enabled.
    """
    allow_read_replies: Annotated[bool | None, Field(title='Allow Read Replies')] = True
    """
    Whether the agent may list recent posts and read their replies.
    """
    allow_reply: Annotated[bool | None, Field(title='Allow Reply')] = True
    """
    Whether the agent may reply to posts or comments. On X self-serve accounts, replying to another user's post is only permitted when that user has @mentioned the connected account.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class XPostToolDefinition(BaseModel):
    """
    Tool definition for X Post tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['x_post'], Field(title='Type')]
    """
    Tool type.
    """
    config: XPostConfig
    """
    X Post configuration.
    """


class YemeksepetiConfig(BaseModel):
    """
    Configuration for the Yemeksepeti tool.

    Looks up order detail, updates order status, and lists recent orders,
    during a live conversation, through a previously connected Yemeksepeti
    partner account. The account is fixed when the tool is configured; the
    LLM only supplies order details at call time.
    """

    yemeksepeti_config_id: Annotated[int, Field(title='Yemeksepeti Config Id')]
    """
    ID of the Yemeksepeti integration configuration (connected partner account) to use.
    """
    allow_get_order_detail: Annotated[
        bool | None, Field(title='Allow Get Order Detail')
    ] = True
    """
    Whether the agent may fetch a single order's detail through this tool.
    """
    allow_update_order_status: Annotated[
        bool | None, Field(title='Allow Update Order Status')
    ] = True
    """
    Whether the agent may update an order's status through this tool.
    """
    allow_list_orders: Annotated[bool | None, Field(title='Allow List Orders')] = True
    """
    Whether the agent may list recent orders through this tool.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType12 | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class YemeksepetiToolDefinition(BaseModel):
    """
    Tool definition for Yemeksepeti tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['yemeksepeti'], Field(title='Type')]
    """
    Tool type.
    """
    config: YemeksepetiConfig
    """
    Yemeksepeti configuration.
    """


class CreateCalendarEntryRequest(BaseModel):
    """
    Request to manually create a calendar entry or scheduled trigger.
    """

    entry_type: Annotated[str | None, Field(title='Entry Type')] = 'note'
    """
    Entry type: note, appointment, reminder, todo, trigger, campaign_event.
    """
    date: Annotated[str, Field(title='Date')]
    """
    Date in YYYY-MM-DD format.
    """
    end_date: Annotated[str | None, Field(title='End Date')] = None
    """
    Optional end date in YYYY-MM-DD format.
    """
    time: Annotated[str | None, Field(title='Time')] = None
    """
    Optional time in HH:MM format.
    """
    title: Annotated[str, Field(max_length=255, min_length=1, title='Title')]
    """
    Entry title.
    """
    description: Annotated[str | None, Field(title='Description')] = None
    """
    Optional description.
    """
    action_type: Annotated[str | None, Field(title='Action Type')] = None
    """
    Trigger action: workflow_run, agent_team_run, campaign_start, campaign_pause.
    """
    action_target_uuid: Annotated[str | None, Field(title='Action Target Uuid')] = None
    """
    UUID of the workflow, id of the agent team, or id of the campaign to act on.
    """
    action_mode: Annotated[str | None, Field(title='Action Mode')] = None
    """
    Workflow run mode when action_type is workflow_run.
    """
    action_channel: Annotated[str | None, Field(title='Action Channel')] = None
    """
    Dispatch channel for workflow_run triggers: phone, whatsapp, telegram, instagram, or text (default).
    """
    action_channel_configuration_id: Annotated[
        int | None, Field(title='Action Channel Configuration Id')
    ] = None
    """
    Channel configuration id, required for whatsapp/telegram/instagram.
    """
    action_telephony_configuration_id: Annotated[
        int | None, Field(title='Action Telephony Configuration Id')
    ] = None
    """
    Telephony configuration id to dial through for the phone channel.
    """
    action_target: Annotated[str | None, Field(title='Action Target')] = None
    """
    Destination phone number or chat id for the trigger's channel.
    """
    recurrence_rule: RecurrenceRule | None = None
    """
    Optional recurrence for trigger entries.
    """


class DocumentListResponseSchema(BaseModel):
    """
    Response schema for list of documents.
    """

    documents: Annotated[list[DocumentResponseSchema], Field(title='Documents')]
    total: Annotated[int, Field(title='Total')]
    limit: Annotated[int, Field(title='Limit')]
    offset: Annotated[int, Field(title='Offset')]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class HttpApiConfig(BaseModel):
    """
    Configuration for HTTP API tools.
    """

    method: Annotated[Method, Field(title='Method')]
    """
    HTTP method to use for the request.
    """
    url: Annotated[str, Field(title='Url')]
    """
    Target HTTP or HTTPS URL.
    """
    headers: Annotated[dict[str, str] | None, Field(title='Headers')] = None
    """
    Static headers to include with every request.
    """
    credential_uuid: Annotated[str | None, Field(title='Credential Uuid')] = None
    """
    Reference to an external credential for request authentication.
    """
    parameters: Annotated[list[ToolParameter] | None, Field(title='Parameters')] = None
    """
    Parameters the model must provide when calling this tool.
    """
    preset_parameters: Annotated[
        list[PresetToolParameter] | None, Field(title='Preset Parameters')
    ] = None
    """
    Parameters injected by Verasist from fixed values or workflow context templates.
    """
    timeout_ms: Annotated[
        TimeoutMs | None, Field(title='Timeout Ms', validate_default=True)
    ] = 5000
    """
    Request timeout in milliseconds.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play after tool execution.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """


class HttpApiToolDefinition(BaseModel):
    """
    Tool definition for HTTP API tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['http_api'], Field(title='Type')]
    """
    Tool type.
    """
    config: HttpApiConfig
    """
    HTTP API configuration.
    """


class PropertySpec(BaseModel):
    """
    Single field on a node.

    `description` is HUMAN-FACING — shown under the field in the edit
    dialog. Keep it concise and explain what the field does.

    `llm_hint` is LLM-FACING — appears only in the `get_node_type` MCP
    response and in SDK schema output. Use it for catalog tool references
    (e.g., "Use `list_recordings`"), array shape, expected value idioms,
    or anything that would be noise in the UI. Optional; omit when the
    `description` already suffices for both audiences.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    type: PropertyType
    display_name: Annotated[str, Field(title='Display Name')]
    description: Annotated[str, Field(min_length=1, title='Description')]
    """
    Human-facing explanation shown in the UI.
    """
    llm_hint: Annotated[str | None, Field(title='Llm Hint')] = None
    """
    LLM-only guidance; omitted from the UI.
    """
    default: Annotated[Any | None, Field(title='Default')] = None
    required: Annotated[bool | None, Field(title='Required')] = False
    placeholder: Annotated[str | None, Field(title='Placeholder')] = None
    display_options: DisplayOptions | None = None
    options: Annotated[list[PropertyOption] | None, Field(title='Options')] = None
    properties: Annotated[list[PropertySpec] | None, Field(title='Properties')] = None
    min_value: Annotated[float | None, Field(title='Min Value')] = None
    max_value: Annotated[float | None, Field(title='Max Value')] = None
    min_length: Annotated[int | None, Field(title='Min Length')] = None
    max_length: Annotated[int | None, Field(title='Max Length')] = None
    pattern: Annotated[str | None, Field(title='Pattern')] = None
    editor: Annotated[str | None, Field(title='Editor')] = None
    extra: Annotated[dict[str, Any] | None, Field(title='Extra')] = None


class RecordingListResponseSchema(BaseModel):
    """
    Response schema for list of recordings.
    """

    recordings: Annotated[list[RecordingResponseSchema], Field(title='Recordings')]
    total: Annotated[int, Field(title='Total')]


class CreateToolRequest(BaseModel):
    """
    Request schema for creating a reusable tool.
    """

    name: Annotated[str, Field(max_length=255, title='Name')]
    """
    Display name for the tool.
    """
    description: Annotated[str | None, Field(title='Description')] = None
    """
    Description shown to the agent when deciding whether to call it.
    """
    category: Annotated[Category | None, Field(title='Category')] = 'http_api'
    """
    Tool category. Must match definition.type.
    """
    icon: Annotated[Icon | None, Field(title='Icon', validate_default=True)] = 'globe'
    """
    Lucide icon identifier.
    """
    icon_color: Annotated[
        IconColor | None, Field(title='Icon Color', validate_default=True)
    ] = '#3B82F6'
    """
    Hex color for the tool icon.
    """
    definition: Annotated[
        HttpApiToolDefinition
        | WebPageQueryToolDefinition
        | EndCallToolDefinition
        | TransferCallToolDefinition
        | CalculatorToolDefinition
        | IncomingMessagesToolDefinition
        | CalendarToolDefinition
        | CallHistoryToolDefinition
        | TransferToAssistantToolDefinition
        | SendMessageToolDefinition
        | TransferToChannelToolDefinition
        | McpToolDefinition
        | EmailToolDefinition
        | GoogleTasksToolDefinition
        | GoogleCalendarToolDefinition
        | GoogleSheetsToolDefinition
        | TrendyolToolDefinition
        | YemeksepetiToolDefinition
        | CrmToolDefinition
        | MediaGenerationToolDefinition
        | InstagramPostToolDefinition
        | FacebookPostToolDefinition
        | LinkedInPostToolDefinition
        | TikTokPostToolDefinition
        | ThreadsPostToolDefinition
        | XPostToolDefinition
        | WordPressPostToolDefinition,
        Field(discriminator='type', title='Definition'),
    ]
    """
    Typed tool definition.
    """


class NodeSpec(BaseModel):
    """
    Single source of truth for a node type.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    display_name: Annotated[str, Field(title='Display Name')]
    description: Annotated[str, Field(min_length=1, title='Description')]
    """
    Human-facing explanation shown in AddNodePanel.
    """
    llm_hint: Annotated[str | None, Field(title='Llm Hint')] = None
    """
    LLM-only guidance; omitted from the UI.
    """
    category: NodeCategory
    icon: Annotated[str, Field(title='Icon')]
    version: Annotated[str | None, Field(title='Version')] = '1.0.0'
    properties: Annotated[list[PropertySpec], Field(title='Properties')]
    examples: Annotated[list[NodeExample] | None, Field(title='Examples')] = None
    graph_constraints: GraphConstraints | None = None


class NodeTypesResponse(BaseModel):
    spec_version: Annotated[str, Field(title='Spec Version')]
    node_types: Annotated[list[NodeSpec], Field(title='Node Types')]


PropertySpec.model_rebuild()
